language: ruby
script: rake spec:travis
before_script: travis_retry rake spec:travis:deps

branches:
  only:
    - master
    - 1-6-stable
    - 1-5-stable
    - 1-3-stable
    - 1-2-stable
    - 1-1-stable
    - 1-0-stable

notifications:
  email: false

rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - 1.8.7

# Rubygems versions MUST be available as rake tasks
# see Rakefile:66 for the list of possible RGV values
env:
  # We need to know if changes to rubygems will break bundler on release
  - RGV=master
  # Test the latest rubygems release with all of our supported rubies
  - RGV=v2.3.0

matrix:
  fast_finish: true
  include:
    # Ruby 2.1, Rubygems 2.2.2 and up
    - rvm: 2.1.2
      env: RGV=v2.2.2
    # Ruby 2.0.0, Rubygems 2.0 and up
    - rvm: 2.0.0
      env: RGV=v2.2.2
    - rvm: 2.0.0
      env: RGV=v2.1.11
    - rvm: 2.0.0
      env: RGV=v2.0.14
    # Ruby 1.9.3, Rubygems 1.5.3 and up
    - rvm: 1.9.3
      env: RGV=v2.2.2
    - rvm: 1.9.3
      env: RGV=v2.1.11
    - rvm: 1.9.3
      env: RGV=v2.0.14
    - rvm: 1.9.3
      env: RGV=v1.8.29
    - rvm: 1.9.3
      env: RGV=v1.7.2
    - rvm: 1.9.3
      env: RGV=v1.6.2
    - rvm: 1.9.3
      env: RGV=v1.5.3
    # Ruby 1.8.7, Rubygems 1.3.6 and up
    - rvm: 1.8.7
      env: RGV=v2.2.2
    - rvm: 1.8.7
      env: RGV=v2.0.14
    - rvm: 1.8.7
      env: RGV=v1.8.29
    - rvm: 1.8.7
      env: RGV=v1.7.2
    - rvm: 1.8.7
      env: RGV=v1.6.2
    - rvm: 1.8.7
      env: RGV=v1.5.3
    - rvm: 1.8.7
      env: RGV=v1.4.2
    - rvm: 1.8.7
      env: RGV=v1.3.7
    - rvm: 1.8.7
      env: RGV=v1.3.6

    # ALLOWED FAILURES
    # For no apparent reason, this often goes over the Travis limit
    - rvm: 1.8.7
      env: RGV=v2.1.11
    # Ruby 1.9.2 sanity check
    # (but it's just too slow and sometimes goes over the Travis limit)
    - rvm: 1.9.2
      env: RGV=v2.3.0
    # Ruby-head (we want to know how we're doing, but not fail the build)
    - rvm: ruby-head
      env: RGV=master
    # JRuby, the latest (not maintained, but good to know)
    - rvm: jruby
      env: RGV=v2.3.0
    # Rubinius, the latest (not maintained, but good to know)
    - rvm: rbx-2
      env: RGV=v2.3.0
  allow_failures:
    - rvm: 1.8.7
      env: RGV=v2.1.11
    - rvm: 1.9.2
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-2
